### ISSUE TITLE
Not able to log in as customer in subshop

### ISSUE THREAD

**Issue by ocjojo** [shyim/ShyimLanguageShopSession#3]
When this Plugin is enabled the backend function to log in as a customer  ("Als dieser Kunde einloggen") is not working for a customer that is assigned to a subshop.

More specifically:
the main shop (ID 1) is german and the subshop (ID 2) is english. For a customer assigned to the main shop backend login works as intended. For a customer assigned to the english subshop it is not working.
The shop is opened and redirected to the english subshop, but no customer is logged in.

My first investigation points to the SessionFactory. When it is not decorated, everything works.
Not sure where to look further. Maybe I could solve the problem and create a PR with some pointers what may be the cause.

**Comment by shyim** [comment]
Just update to Shopware 5.6. I wont update this plugin anymore

**Comment by ocjojo** [comment]
Absolutely! Sorry for wasting your time and thank you for the fast response.
We already are on 5.6 and could indeed just delete the plugin. I didn't know it was there mostly as a "bugfix". I took over the project with the plugin already there.
